services:
  mongo:
    image: mongo:6
    ports: ["27017:27017"]
    volumes: [mongo-data:/data/db]

  backend:
    build: ./backend
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://mongo:27017/benibox   # ← URI unique
      JWT_SECRET: change_this
      PORT: 3001
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports: ["3001:3001"]
    depends_on: [mongo]
    command: npm run dev

  seed:
    build: ./backend
    command: npm run seed
    environment:
      MONGODB_URI: mongodb://mongo:27017/benibox
      ADMIN_EMAIL: admin@demo.com
      ADMIN_PASSWORD: Admin123!
    depends_on: [mongo]
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      target: build
    environment:
      VITE_BACKEND_URL: http://localhost:3001
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports: ["5173:5173"]
    command: ["npm","run","dev","--","--host","0.0.0.0","--port","5173"]
    depends_on: [backend]

volumes:
  mongo-data:
